---
- name: Hello world playbook
  hosts: awx_target_servers
  tasks: 
    - name: Display hello message
      debug: 
        msg: "Hello world!"

    - name: Check value of AWX privata data directory      
      set_fact: 
        awx_priv_data_dir: "{{ lookup('env','AWX_PRIVATE_DATA_DIR') }}"

    - name: Get content inside AWX privata data directory
      command: ls -ltr "{{ awx_priv_data_dir }}"
      register: dir_contents

    - name: Show contents of AWX_PRIVATE_DATA_DIR
      debug:
        var: dir_contents.stdout_lines    

